/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import type { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "agent": {
        "router": string;
        "routerDesc": string;
        "researcher": string;
        "researcherDesc": string;
        "author": string;
        "authorDesc": string;
        "reviewer": string;
        "reviewerDesc": string;
        "drafter": string;
        "drafterDesc": string;
        "planner": string;
        "plannerDesc": string;
        "extractor": string;
        "extractorDesc": string;
        "glossarist": string;
        "glossaristDesc": string;
        "transcriber": string;
        "transcriberDesc": string;
        "curator": string;
        "curatorDesc": string;
        "architect": string;
        "architectDesc": string;
        "route": {
            "explicit": string;
            "disabled": string;
            "wrongSurface": string;
            "noProvider": string;
            "modelLacks": string;
            "noCandidate": string;
            "onlyCandidate": string;
            "noRequestText": string;
            "noClassifier": string;
            "fellBackTo": string;
            "noUsableAnswer": string;
        };
        "curation": {
            "noPages": string;
            "orphanTitle": string;
            "orphanDetail": string;
            "summary": string;
        };
    };
    "assistant": {
        "disabled": string;
        "note": {
            "published": string;
            "mergeRequest": string;
            "formShown": string;
            "agentOffered": string;
        };
    };
    "import": {
        "stage": {
            "reading-file": string;
            "reading-document": string;
            "reading-image": string;
            "reading-rows": string;
            "opening-pdf": string;
            "unpacking-deck": string;
            "checking-vision": string;
            "converting": string;
            "building-sections": string;
            "building-table": string;
            "rebuilding-structure": string;
            "formatting": string;
            "parsing": string;
        };
        "warning": {
            "passthrough": string;
            "remoteImages": {
                "one": string;
                "other": string;
                "few": string;
                "many": string;
            };
            "htmlFurnitureDropped": string;
            "noLegibleText": string;
            "scannedPdf": string;
            "noHeadings": string;
            "runningHeads": {
                "one": string;
                "other": string;
                "few": string;
                "many": string;
            };
            "frontmatterKept": string;
            "rejoinedLines": string;
            "imagesAttached": {
                "one": string;
                "other": string;
                "few": string;
                "many": string;
            };
            "speakerNotes": {
                "one": string;
                "other": string;
                "few": string;
                "many": string;
            };
            "slideChromeDropped": string;
            "invalidStructured": string;
            "singleCodeBlock": string;
            "rowsTruncated": string;
            "wideTable": string;
        };
    };
    "mention": {
        "failed": string;
        "timedOut": string;
        "unknownAgent": string;
        "agentDisabled": string;
        "providerDisabled": string;
        "notConversational": string;
        "modelMissing": string;
    };
    "notification": {
        "passwordReset": {
            "subject": string;
            "body": string;
        };
    };
    "prompt": {
        "localeDirective": string;
    };
    "role": {
        "viewer": string;
        "editor": string;
        "admin": string;
    };
    "status": {
        "mr": {
            "open": string;
            "merged": string;
            "closed": string;
        };
        "revision": {
            "draft": string;
            "finalized": string;
            "indexing": string;
            "indexed": string;
            "failed": string;
        };
        "import": {
            "awaiting-upload": string;
            "queued": string;
            "running": string;
            "parsed": string;
            "submitted": string;
            "failed": string;
        };
        "node": {
            "pending": string;
            "running": string;
            "awaiting-review": string;
            "approved": string;
            "materializing": string;
            "published": string;
            "rejected": string;
            "skipped": string;
            "failed": string;
        };
        "run": {
            "pending": string;
            "running": string;
            "awaiting-review": string;
            "completed": string;
            "paused": string;
            "cancelled": string;
            "failed": string;
        };
    };
    "subject": {
        "workspaceId": string;
        "workspace": string;
        "document": string;
        "mergeRequest": string;
        "job": string;
        "project": string;
        "assistantThread": string;
        "skill": string;
        "plugin": string;
        "provider": string;
        "glossaryTerm": string;
        "import": string;
        "workflow": string;
        "workflowRun": string;
        "connector": string;
        "connectorRun": string;
        "id": string;
        "savedFilter": string;
        "sourcePolicy": string;
    };
    "validation": {
        "isDefined": string;
        "isNotEmpty": string;
        "isString": string;
        "isNumber": string;
        "isInt": string;
        "isBoolean": string;
        "isArray": string;
        "isObject": string;
        "isEnum": string;
        "isEmail": string;
        "isUrl": string;
        "isUuid": string;
        "isDateString": string;
        "isIn": string;
        "isPositive": string;
        "min": string;
        "max": string;
        "minLength": string;
        "maxLength": string;
        "arrayMinSize": string;
        "arrayMaxSize": string;
        "arrayNotEmpty": string;
        "matches": string;
        "hexColor": string;
    };
    "workflow": {
        "issue": {
            "empty": string;
            "badId": string;
            "duplicateId": string;
            "unknownKind": string;
            "missingTitle": string;
            "unknownTarget": string;
            "selfLoop": string;
            "missingPrompt": string;
            "producesNeedsCategory": string;
            "deadEnd": string;
            "maxItemsRange": string;
            "fanOutIgnored": string;
            "cycle": string;
            "noEntry": string;
            "manyEntries": string;
        };
        "transition": {
            "badEvent": string;
            "badNodeEvent": string;
        };
        "draft": {
            "needMore": string;
            "designed": string;
        };
    };
    "ws": {
        "disabled": string;
        "subscriptionLimit": string;
        "workspaceRequired": string;
        "badMessage": string;
        "unauthorized": string;
        "unknownType": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
