/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import type { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "agent": {
        "router": string;
        "routerDesc": string;
        "researcher": string;
        "researcherDesc": string;
        "author": string;
        "authorDesc": string;
        "reviewer": string;
        "reviewerDesc": string;
        "drafter": string;
        "drafterDesc": string;
        "planner": string;
        "plannerDesc": string;
        "extractor": string;
        "extractorDesc": string;
        "glossarist": string;
        "glossaristDesc": string;
        "transcriber": string;
        "transcriberDesc": string;
        "curator": string;
        "curatorDesc": string;
        "architect": string;
        "architectDesc": string;
        "route": {
            "explicit": string;
            "disabled": string;
            "wrongSurface": string;
            "noProvider": string;
            "modelLacks": string;
            "noCandidate": string;
            "onlyCandidate": string;
            "noRequestText": string;
            "noClassifier": string;
            "fellBackTo": string;
            "noUsableAnswer": string;
        };
        "curation": {
            "noPages": string;
            "orphanTitle": string;
            "orphanDetail": string;
            "summary": string;
        };
    };
    "assistant": {
        "disabled": string;
        "note": {
            "published": string;
            "mergeRequest": string;
            "formShown": string;
            "agentOffered": string;
        };
    };
    "connector": {
        "stage": {
            "connecting": string;
            "listing": string;
            "fetching": string;
            "writing": string;
            "pushing": string;
            "finishing": string;
        };
        "branch": {
            "conflict": string;
        };
        "mr": {
            "title": string;
            "description": string;
        };
        "warning": {
            "passthrough": string;
            "pushUnsupported": string;
            "documentMissing": string;
            "conflict": string;
            "orphan": string;
            "orphansFound": string;
            "discoveryStopped": string;
            "reRooted": string;
        };
        "pushVersionMessage": string;
        "syncRevisionMessage": string;
        "stoppedAtMax": string;
        "revertRevisionMessage": string;
    };
    "error": {
        "internal": string;
        "invalidUuid": string;
        "auth": {
            "missingBearer": string;
            "invalidSession": string;
            "accountDisabled": string;
            "unknownApiKey": string;
            "invalidCredentials": string;
            "invalidResetToken": string;
            "noPasswordInDevMode": string;
            "currentPasswordIncorrect": string;
            "signupDisabled": string;
            "emailTaken": string;
            "platformAdminRequired": string;
            "notMember": string;
            "roleRequired": string;
            "runOwnerUnavailable": string;
            "trustedOperatorRequired": string;
            "noApiKeyInDevMode": string;
        };
        "workspace": {
            "notFound": string;
            "noUserWithEmail": string;
            "notAMember": string;
            "lastAdminDemote": string;
            "lastAdminRemove": string;
        };
        "user": {
            "notFound": string;
            "cannotDisableSelf": string;
            "cannotRemoveOwnAdmin": string;
        };
        "project": {
            "notFound": string;
            "notInWorkspace": string;
            "nothingToUpdate": string;
            "notEmpty": string;
            "moveToSelf": string;
            "confirmName": string;
            "lastInWorkspace": string;
        };
        "document": {
            "notFound": string;
            "notFoundInWorkspace": string;
            "noRevisions": string;
            "noReadableRevision": string;
            "parentNotInProject": string;
            "selfParent": string;
            "moveCycle": string;
            "nothingToUpdate": string;
            "contentIsDraft": string;
            "uploadMissing": string;
            "revisionNotDraft": string;
        };
        "branch": {
            "notFound": string;
            "exists": string;
            "headMoved": string;
            "needsFinalized": string;
        };
        "revision": {
            "notFoundOnDocument": string;
            "notComparable": string;
        };
        "compare": {
            "badMode": string;
        };
        "relations": {
            "missingParams": string;
        };
        "mergeRequest": {
            "notFound": string;
            "sameBranches": string;
            "sourceNotFinalized": string;
            "branchNoRevisions": string;
            "targetNoRevisions": string;
            "notOpenForEdit": string;
            "notOpenForApproval": string;
            "notOpenForClose": string;
            "notOpenForMerge": string;
            "notOpenForReviewers": string;
            "notClosedForReopen": string;
            "discussionsReadOnly": string;
            "concurrentChange": string;
            "isDraft": string;
            "needsApprovals": string;
            "nothingToMerge": string;
            "diverged": string;
            "divergedWhileMerging": string;
            "alreadyOpen": string;
            "notMembers": string;
        };
        "thread": {
            "notFoundOnDocument": string;
            "notFoundOnMergeRequest": string;
            "plainComment": string;
        };
        "comment": {
            "notFoundOnThread": string;
            "onlyAuthorCanEdit": string;
            "onlyAuthorCanDelete": string;
        };
        "anchor": {
            "line": string;
            "text": string;
            "section": string;
            "entity": string;
        };
        "entity": {
            "notFound": string;
        };
        "graph": {
            "selectOnly": string;
            "singleStatement": string;
            "writeKeyword": string;
        };
        "glossary": {
            "notFound": string;
            "duplicate": string;
            "documentNotFound": string;
        };
        "attachment": {
            "tooLarge": string;
            "documentNotFound": string;
            "uploadMissing": string;
            "notFound": string;
        };
        "import": {
            "notFound": string;
            "unsupportedFormat": string;
            "tooLarge": string;
            "alreadySubmitted": string;
            "uploadMissing": string;
            "notReviewable": string;
            "notSubmittable": string;
            "imageNotFound": string;
            "revisionVanished": string;
            "parentNotInProject": string;
            "needsVisionModel": string;
        };
        "ingestionJob": {
            "notFound": string;
        };
        "ai": {
            "skillNotFound": string;
            "skillNameTaken": string;
            "pluginNotFound": string;
            "pluginNameTaken": string;
            "providerNotFound": string;
            "providerNameTaken": string;
            "providerUnavailable": string;
            "encryptionKeyMissing": string;
            "pluginUrlInvalid": string;
            "pluginUrlNotHttps": string;
            "pluginHostUnresolved": string;
            "pluginUrlPrivate": string;
            "providerNone": string;
            "agentNotFound": string;
            "agentScheduleNeedsOwner": string;
            "agentScheduleNeedsInterval": string;
            "agentNotBuiltIn": string;
            "agentKeyInvalid": string;
            "agentIsBuiltInCreate": string;
            "agentNameTaken": string;
            "agentIsBuiltInDelete": string;
            "agentUnknownTools": string;
            "agentUnknownSkill": string;
            "agentUnknownProvider": string;
            "agentDisabled": string;
            "agentNotBackground": string;
            "agentRunNotFound": string;
            "agentNoExecutor": string;
            "findingNotFound": string;
            "findingAlreadyProposed": string;
            "findingInFlight": string;
            "findingNoDocument": string;
            "findingOrphan": string;
            "findingDocumentGone": string;
            "assistantDisabled": string;
            "drafterCannot": string;
            "draftRevisionGone": string;
            "noReadableContent": string;
            "emptyPage": string;
            "agentRunInFlight": string;
        };
        "assistant": {
            "providerDisabled": string;
            "threadNotFound": string;
            "messageNotFound": string;
            "budgetUser": string;
            "budgetWorkspace": string;
        };
        "workflow": {
            "notFound": string;
            "runNotFound": string;
            "nodeNotFound": string;
            "nameTaken": string;
            "runsInFlight": {
                "one": string;
                "other": string;
                "few": string;
                "many": string;
            };
            "disabled": string;
            "differentProject": string;
            "runInFlightForPage": string;
            "nodeNotAwaitingReview": string;
            "stepGone": string;
            "invalidGraph": string;
        };
        "connector": {
            "notFound": string;
            "runNotFound": string;
            "linkNotFound": string;
            "nameTaken": string;
            "unknownKind": string;
            "missingField": string;
            "credentialRequired": string;
            "encryptionKeyMissing": string;
            "urlInvalid": string;
            "urlNotHttps": string;
            "urlPrivate": string;
            "hostUnresolved": string;
            "disabled": string;
            "pullNotSupported": string;
            "pushNotSupported": string;
            "directionNotAllowed": string;
            "runInFlight": string;
            "webhookNotConfigured": string;
            "webhookInvalidSignature": string;
            "notLinked": string;
            "itemNotFound": string;
            "itemNotEditable": string;
            "itemNotApplied": string;
            "itemEvent": string;
            "runEvent": string;
            "revertHasChildren": string;
            "revertNoPrevious": string;
            "aiEmpty": string;
            "mergeNotAConflict": string;
        };
        "routeNotFound": string;
        "validationFailed": string;
        "savedFilter": {
            "notFound": string;
            "duplicate": string;
        };
        "invalidNumericId": string;
        "activity": {
            "actorRequired": string;
            "rangeInverted": string;
            "rangeTooWide": string;
        };
        "avatar": {
            "unsupportedType": string;
            "tooLarge": string;
            "notUploaded": string;
            "none": string;
            "forbidden": string;
            "noDevAvatar": string;
        };
        "notification": {
            "subjectNotInWorkspace": string;
            "nothingToMark": string;
        };
        "web": {
            "notFound": string;
            "invalidPattern": string;
            "allowlistEmpty": string;
            "searchUnconfigured": string;
            "searchFailed": string;
            "fetchStatus": string;
            "fetchRedirects": string;
            "fetchType": string;
            "fetchFailed": string;
            "fetchEmpty": string;
            "remedy": string;
            "denied": {
                "mode-off": string;
                "not-allowlisted": string;
                "blocked": string;
                "unsafe": string;
            };
        };
    };
    "import": {
        "stage": {
            "reading-file": string;
            "reading-document": string;
            "reading-image": string;
            "reading-rows": string;
            "opening-pdf": string;
            "unpacking-deck": string;
            "checking-vision": string;
            "converting": string;
            "building-sections": string;
            "building-table": string;
            "rebuilding-structure": string;
            "formatting": string;
            "parsing": string;
        };
        "warning": {
            "passthrough": string;
            "remoteImages": {
                "one": string;
                "other": string;
                "few": string;
                "many": string;
            };
            "htmlFurnitureDropped": string;
            "noLegibleText": string;
            "scannedPdf": string;
            "noHeadings": string;
            "runningHeads": {
                "one": string;
                "other": string;
                "few": string;
                "many": string;
            };
            "frontmatterKept": string;
            "rejoinedLines": string;
            "imagesAttached": {
                "one": string;
                "other": string;
                "few": string;
                "many": string;
            };
            "speakerNotes": {
                "one": string;
                "other": string;
                "few": string;
                "many": string;
            };
            "slideChromeDropped": string;
            "invalidStructured": string;
            "singleCodeBlock": string;
            "rowsTruncated": string;
            "wideTable": string;
        };
    };
    "mention": {
        "failed": string;
        "timedOut": string;
        "unknownAgent": string;
        "agentDisabled": string;
        "providerDisabled": string;
        "notConversational": string;
        "modelMissing": string;
    };
    "notification": {
        "passwordReset": {
            "subject": string;
            "body": string;
        };
    };
    "prompt": {
        "localeDirective": string;
    };
    "role": {
        "viewer": string;
        "editor": string;
        "admin": string;
    };
    "status": {
        "mr": {
            "open": string;
            "merged": string;
            "closed": string;
        };
        "revision": {
            "draft": string;
            "finalized": string;
            "indexing": string;
            "indexed": string;
            "failed": string;
        };
        "import": {
            "awaiting-upload": string;
            "queued": string;
            "running": string;
            "parsed": string;
            "submitted": string;
            "failed": string;
        };
        "node": {
            "pending": string;
            "running": string;
            "awaiting-review": string;
            "approved": string;
            "materializing": string;
            "published": string;
            "rejected": string;
            "skipped": string;
            "failed": string;
        };
        "run": {
            "pending": string;
            "running": string;
            "awaiting-review": string;
            "completed": string;
            "paused": string;
            "cancelled": string;
            "failed": string;
        };
    };
    "subject": {
        "workspaceId": string;
        "workspace": string;
        "document": string;
        "mergeRequest": string;
        "job": string;
        "project": string;
        "assistantThread": string;
        "skill": string;
        "plugin": string;
        "provider": string;
        "glossaryTerm": string;
        "import": string;
        "workflow": string;
        "workflowRun": string;
        "connector": string;
        "connectorRun": string;
        "id": string;
        "savedFilter": string;
        "sourcePolicy": string;
    };
    "validation": {
        "isDefined": string;
        "isNotEmpty": string;
        "isString": string;
        "isNumber": string;
        "isInt": string;
        "isBoolean": string;
        "isArray": string;
        "isObject": string;
        "isEnum": string;
        "isEmail": string;
        "isUrl": string;
        "isUuid": string;
        "isDateString": string;
        "isIn": string;
        "isPositive": string;
        "min": string;
        "max": string;
        "minLength": string;
        "maxLength": string;
        "arrayMinSize": string;
        "arrayMaxSize": string;
        "arrayNotEmpty": string;
        "matches": string;
        "hexColor": string;
    };
    "workflow": {
        "issue": {
            "empty": string;
            "badId": string;
            "duplicateId": string;
            "unknownKind": string;
            "missingTitle": string;
            "unknownTarget": string;
            "selfLoop": string;
            "missingPrompt": string;
            "producesNeedsCategory": string;
            "deadEnd": string;
            "maxItemsRange": string;
            "fanOutIgnored": string;
            "cycle": string;
            "noEntry": string;
            "manyEntries": string;
        };
        "transition": {
            "badEvent": string;
            "badNodeEvent": string;
        };
        "draft": {
            "needMore": string;
            "designed": string;
        };
    };
    "ws": {
        "disabled": string;
        "subscriptionLimit": string;
        "workspaceRequired": string;
        "badMessage": string;
        "unauthorized": string;
        "unknownType": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
