/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import type { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "assistant": {
        "disabled": string;
        "note": {
            "published": string;
            "mergeRequest": string;
            "formShown": string;
            "agentOffered": string;
        };
    };
    "error": {
        "internal": string;
        "invalidUuid": string;
        "auth": {
            "missingBearer": string;
            "invalidSession": string;
            "accountDisabled": string;
            "unknownApiKey": string;
            "invalidCredentials": string;
            "invalidResetToken": string;
            "noPasswordInDevMode": string;
            "currentPasswordIncorrect": string;
            "signupDisabled": string;
            "emailTaken": string;
            "platformAdminRequired": string;
            "notMember": string;
            "roleRequired": string;
            "trustedOperatorRequired": string;
        };
        "workspace": {
            "notFound": string;
            "noUserWithEmail": string;
            "notAMember": string;
            "lastAdminDemote": string;
            "lastAdminRemove": string;
        };
        "user": {
            "notFound": string;
            "cannotDisableSelf": string;
            "cannotRemoveOwnAdmin": string;
        };
        "project": {
            "notFound": string;
            "notInWorkspace": string;
            "nothingToUpdate": string;
            "notEmpty": {
                "one": string;
                "other": string;
                "few": string;
                "many": string;
            };
            "lastInWorkspace": string;
        };
        "document": {
            "notFound": string;
            "notFoundInWorkspace": string;
            "noRevisions": string;
            "noReadableRevision": string;
            "parentNotInProject": string;
            "selfParent": string;
            "moveCycle": string;
            "nothingToUpdate": string;
            "contentIsDraft": string;
            "uploadMissing": string;
            "revisionNotDraft": string;
        };
        "branch": {
            "notFound": string;
            "exists": string;
            "headMoved": string;
            "needsFinalized": string;
        };
        "revision": {
            "notFoundOnDocument": string;
            "notComparable": string;
        };
        "compare": {
            "badMode": string;
        };
        "relations": {
            "missingParams": string;
        };
        "mergeRequest": {
            "notFound": string;
            "sameBranches": string;
            "sourceNotFinalized": string;
            "branchNoRevisions": string;
            "targetNoRevisions": string;
            "notOpenForEdit": string;
            "notOpenForApproval": string;
            "notOpenForClose": string;
            "notOpenForMerge": string;
            "notOpenForReviewers": string;
            "notClosedForReopen": string;
            "discussionsReadOnly": string;
            "concurrentChange": string;
            "isDraft": string;
            "needsApprovals": string;
            "nothingToMerge": string;
            "diverged": string;
            "divergedWhileMerging": string;
            "alreadyOpen": string;
            "notMembers": string;
        };
        "thread": {
            "notFoundOnDocument": string;
            "notFoundOnMergeRequest": string;
            "plainComment": string;
        };
        "comment": {
            "notFoundOnThread": string;
            "onlyAuthorCanEdit": string;
            "onlyAuthorCanDelete": string;
        };
        "anchor": {
            "line": string;
            "text": string;
            "section": string;
            "entity": string;
        };
        "entity": {
            "notFound": string;
        };
        "graph": {
            "selectOnly": string;
            "singleStatement": string;
            "writeKeyword": string;
        };
        "glossary": {
            "notFound": string;
            "duplicate": string;
            "documentNotFound": string;
        };
        "attachment": {
            "tooLarge": string;
            "documentNotFound": string;
            "uploadMissing": string;
            "notFound": string;
        };
        "import": {
            "notFound": string;
            "unsupportedFormat": string;
            "tooLarge": string;
            "alreadySubmitted": string;
            "uploadMissing": string;
            "notReviewable": string;
            "notSubmittable": string;
            "imageNotFound": string;
            "revisionVanished": string;
            "parentNotInProject": string;
            "needsVisionModel": string;
        };
        "ingestionJob": {
            "notFound": string;
        };
        "ai": {
            "skillNotFound": string;
            "skillNameTaken": string;
            "pluginNotFound": string;
            "pluginNameTaken": string;
            "providerNotFound": string;
            "providerNameTaken": string;
            "providerUnavailable": string;
            "encryptionKeyMissing": string;
            "pluginUrlInvalid": string;
            "pluginUrlNotHttps": string;
            "pluginHostUnresolved": string;
            "pluginUrlPrivate": string;
            "providerNone": string;
        };
        "assistant": {
            "providerDisabled": string;
            "threadNotFound": string;
            "messageNotFound": string;
            "budgetUser": string;
            "budgetWorkspace": string;
        };
        "workflow": {
            "notFound": string;
            "runNotFound": string;
            "nodeNotFound": string;
            "nameTaken": string;
            "runsInFlight": {
                "one": string;
                "other": string;
                "few": string;
                "many": string;
            };
            "disabled": string;
            "differentProject": string;
            "runInFlightForPage": string;
            "nodeNotAwaitingReview": string;
            "stepGone": string;
            "invalidGraph": string;
        };
        "routeNotFound": string;
        "validationFailed": string;
    };
    "import": {
        "stage": {
            "reading-file": string;
            "reading-document": string;
            "reading-image": string;
            "reading-rows": string;
            "opening-pdf": string;
            "unpacking-deck": string;
            "checking-vision": string;
            "converting": string;
            "building-sections": string;
            "building-table": string;
            "rebuilding-structure": string;
            "formatting": string;
            "parsing": string;
        };
        "warning": {
            "passthrough": string;
            "remoteImages": {
                "one": string;
                "other": string;
                "few": string;
                "many": string;
            };
            "htmlFurnitureDropped": string;
            "noLegibleText": string;
            "scannedPdf": string;
            "noHeadings": string;
            "runningHeads": {
                "one": string;
                "other": string;
                "few": string;
                "many": string;
            };
            "frontmatterKept": string;
            "rejoinedLines": string;
            "imagesAttached": {
                "one": string;
                "other": string;
                "few": string;
                "many": string;
            };
            "speakerNotes": {
                "one": string;
                "other": string;
                "few": string;
                "many": string;
            };
            "slideChromeDropped": string;
            "invalidStructured": string;
            "singleCodeBlock": string;
            "rowsTruncated": string;
            "wideTable": string;
        };
    };
    "notification": {
        "passwordReset": {
            "subject": string;
            "body": string;
        };
    };
    "prompt": {
        "localeDirective": string;
    };
    "role": {
        "viewer": string;
        "editor": string;
        "admin": string;
    };
    "status": {
        "mr": {
            "open": string;
            "merged": string;
            "closed": string;
        };
        "revision": {
            "draft": string;
            "finalized": string;
            "indexing": string;
            "indexed": string;
            "failed": string;
        };
        "import": {
            "awaiting-upload": string;
            "queued": string;
            "running": string;
            "parsed": string;
            "submitted": string;
            "failed": string;
        };
        "node": {
            "pending": string;
            "running": string;
            "awaiting-review": string;
            "approved": string;
            "materializing": string;
            "published": string;
            "rejected": string;
            "skipped": string;
            "failed": string;
        };
        "run": {
            "pending": string;
            "running": string;
            "awaiting-review": string;
            "completed": string;
            "paused": string;
            "cancelled": string;
            "failed": string;
        };
    };
    "subject": {
        "workspaceId": string;
        "workspace": string;
        "document": string;
        "mergeRequest": string;
        "job": string;
        "project": string;
        "assistantThread": string;
        "skill": string;
        "plugin": string;
        "provider": string;
        "glossaryTerm": string;
        "import": string;
        "workflow": string;
        "workflowRun": string;
        "id": string;
    };
    "validation": {
        "isDefined": string;
        "isNotEmpty": string;
        "isString": string;
        "isNumber": string;
        "isInt": string;
        "isBoolean": string;
        "isArray": string;
        "isObject": string;
        "isEnum": string;
        "isEmail": string;
        "isUrl": string;
        "isUuid": string;
        "isDateString": string;
        "isIn": string;
        "isPositive": string;
        "min": string;
        "max": string;
        "minLength": string;
        "maxLength": string;
        "arrayMinSize": string;
        "arrayMaxSize": string;
        "arrayNotEmpty": string;
        "matches": string;
    };
    "workflow": {
        "issue": {
            "empty": string;
            "badId": string;
            "duplicateId": string;
            "unknownKind": string;
            "missingTitle": string;
            "unknownTarget": string;
            "selfLoop": string;
            "missingPrompt": string;
            "producesNeedsCategory": string;
            "deadEnd": string;
            "maxItemsRange": string;
            "fanOutIgnored": string;
            "cycle": string;
            "noEntry": string;
            "manyEntries": string;
        };
        "transition": {
            "badEvent": string;
            "badNodeEvent": string;
        };
    };
    "ws": {
        "disabled": string;
        "subscriptionLimit": string;
        "workspaceRequired": string;
        "badMessage": string;
        "unauthorized": string;
        "unknownType": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
